"""
cocotb integration tests for the SL processor.

Reads a test.vector file (generated by the C++ Test executable) and drives
the testing_wrapper DUT. The vector file path comes from the TEST_VECTOR
environment variable set by run.py / run_parallel.py.

Vector entry types:
  0000 <name>         — start testcase: clear memories, reset core
  0001 <hex16 ...>    — load 16-bit code words into code memory
  0002 <hex32>        — run N enabled processor cycles
  0003 <hex32>        — run until executed_addr >= value
  0004 <addr32> <dat32> — write data to memory address
  0005 <hex32>        — run N cycles with ext_mem_stall asserted
  000F <addr32> <dat32> — read memory and assert result == expected

Failed test lines are written to FAILED_VECTOR (env var) if any test fails.
"""

import os
import cocotb
from cocotb.clock import Clock
from cocotb.triggers import RisingEdge, Timer

CLK_PERIOD_NS = 20
_ADDR_WAIT_LIMIT_NS = 50_000_000            # 50ms sim time = 2.5M cycles


class _TestMaster:
    """Drives the testing_wrapper's wb_master port (mem_* signals)."""

    def __init__(self, dut):
        self._dut = dut
        self._clk = dut.clk_i

    def idle(self):
        self._dut.mem_addr_i.value = 0
        self._dut.mem_din_i.value  = 0
        self._dut.mem_we_i.value   = 0
        self._dut.mem_en_i.value   = 0

    async def write(self, addr: int, data: int):
        self._dut.mem_addr_i.value = addr
        self._dut.mem_din_i.value  = data
        self._dut.mem_we_i.value   = 1
        self._dut.mem_en_i.value   = 1
        await RisingEdge(self._clk)
        self._dut.mem_en_i.value = 0
        self._dut.mem_we_i.value = 0
        while not self._dut.mem_complete_o.value:
            await RisingEdge(self._clk)
        await RisingEdge(self._clk)

    async def read(self, addr: int) -> int:
        self._dut.mem_addr_i.value = addr
        self._dut.mem_we_i.value   = 0
        self._dut.mem_en_i.value   = 1
        await RisingEdge(self._clk)
        self._dut.mem_en_i.value = 0
        while not self._dut.mem_complete_o.value:
            await RisingEdge(self._clk)
        result = int(self._dut.mem_dout_o.value)
        await RisingEdge(self._clk)
        return result


@cocotb.test()
async def test_from_vector(dut):
    vector_path   = os.environ.get("TEST_VECTOR",   "test.vector")
    failed_vector = os.environ.get("FAILED_VECTOR", "")

    cocotb.start_soon(Clock(dut.clk_i, CLK_PERIOD_NS, unit="ns").start())

    master = _TestMaster(dut)
    master.idle()
    dut.reset_n_i.value            = 0
    dut.enable_core_i.value        = 0
    dut.core_reset_n_i.value       = 1
    dut.ext_mem_stall_i.value      = 0
    dut.force_proc_bus_off_i.value = 0

    await Timer(33, unit="ns")
    dut.reset_n_i.value = 1
    await Timer(200, unit="ns")

    with open(vector_path, "r") as f:
        lines = f.readlines()

    # last_code_len: code words loaded by the PREVIOUS test (for clearing).
    # These are populated during each test and used when the NEXT test starts.
    last_code_len = 0

    current_test_name  = ""
    current_test_lines: list[str] = []
    failed_tests: list[list[str]] = []
    test_failed      = False   # skip remaining 000F lines after first failure in a test
    assertions_passed = 0
    tests_passed      = 0
    tests_failed      = 0

    def _log_test_result():
        if not current_test_name:
            return
        if test_failed:
            cocotb.log.warning(f"[FAIL] {current_test_name}")
        else:
            cocotb.log.info(f"[PASS] {current_test_name}")

    for line in lines:
        line = line.rstrip("\n")
        if not line:
            continue
        entry_type = int(line[:4], 16)
        rest = line[5:].split()

        if entry_type == 0x0000:
            _log_test_result()
            if current_test_name:
                if test_failed:
                    tests_failed += 1
                else:
                    tests_passed += 1

            last_code_len_prev = last_code_len
            last_code_len      = 0

            current_test_name  = line[5:]
            current_test_lines = [line]
            test_failed        = False
            cocotb.log.info(f">> {current_test_name}")
            dut.force_proc_bus_off_i.value = 0
            dut.enable_core_i.value = 0

            # Clear code memory from previous test and all 512 core_mem words.
            # Full core_mem clear matches C++ RTProgTester which zeroes all 512
            # words before each test — static frames rely on zeroed return addrs.
            clear_code = min(last_code_len_prev + 4, 4096)
            for i in range(clear_code):
                await master.write(4096 + i, 0x0000FFFF)
            for addr in range(512):
                await master.write(addr, 0x00000000)

            cocotb.log.info("  clear mem complete")

            dut.enable_core_i.value  = 1
            dut.core_reset_n_i.value = 0
            await Timer(33, unit="ns")
            dut.core_reset_n_i.value = 1

        elif entry_type == 0x0001:
            current_test_lines.append(line)
            dut.enable_core_i.value = 0
            words = rest
            for j, w in enumerate(words):
                await master.write(4096 + j, int(w, 16))
            last_code_len = len(words)
            cocotb.log.info(f"  {len(words)} code words loaded")
            dut.enable_core_i.value = 1

        elif entry_type in (0x0002, 0x0005):
            current_test_lines.append(line)
            n = int(rest[0], 16)
            cocotb.log.info(f"  run {n} cycles")
            dut.ext_mem_stall_i.value = 1 if entry_type == 0x0005 else 0
            for _ in range(n):
                await RisingEdge(dut.clk_i)
            dut.ext_mem_stall_i.value = 0

        elif entry_type == 0x0003:
            current_test_lines.append(line)
            target = int(rest[0], 16)
            cocotb.log.info(f"  run until addr {target}")
            waited_ns = 0
            timed_out = False
            # Poll every clock cycle: executed_addr_o is only >= target briefly
            # when the program passes through (GOTO may drop the PC below target).
            while True:
                await RisingEdge(dut.clk_i)
                waited_ns += CLK_PERIOD_NS
                try:
                    cur = int(dut.executed_addr_o.value)
                    if cur >= target:
                        break
                except ValueError:
                    pass
                if waited_ns >= _ADDR_WAIT_LIMIT_NS:
                    try:
                        cur_addr = int(dut.executed_addr_o.value)
                    except ValueError:
                        cur_addr = -1
                    cocotb.log.error(
                        f"[{current_test_name}] TIMEOUT: executed_addr never reached "
                        f"{target:#x} after {waited_ns // 1_000_000}ms sim time "
                        f"(stuck at {cur_addr:#x})"
                    )
                    if not test_failed:
                        failed_tests.append(list(current_test_lines))
                        failed += 1
                        test_failed = True
                    timed_out = True
                    break
            if not timed_out:
                cocotb.log.info("  complete")

        elif entry_type == 0x0004:
            current_test_lines.append(line)
            addr = int(rest[0], 16) & 0xFFFF
            data = int(rest[1], 16)
            cocotb.log.info(f"  write {data:#010x} → addr {addr}")
            dut.enable_core_i.value        = 0
            dut.force_proc_bus_off_i.value = 1
            await master.write(addr, data)
            dut.force_proc_bus_off_i.value = 0
            dut.enable_core_i.value        = 1

        elif entry_type == 0x000F:
            current_test_lines.append(line)
            if test_failed:
                continue   # skip remaining assertions after first failure in this test
            addr     = int(rest[0], 16) & 0xFFFF
            expected = int(rest[1], 16)
            dut.enable_core_i.value        = 0
            dut.force_proc_bus_off_i.value = 1
            result = await master.read(addr)
            dut.force_proc_bus_off_i.value = 0
            dut.enable_core_i.value        = 1
            if result != expected:
                msg = (f"addr {addr}: got {result:#010x}, expected {expected:#010x}")
                cocotb.log.error(f"  assertion failed: {msg}")
                if not test_failed:
                    failed_tests.append(list(current_test_lines))
                    test_failed = True
            else:
                assertions_passed += 1

    _log_test_result()
    if current_test_name:
        if test_failed:
            tests_failed += 1
        else:
            tests_passed += 1

    cocotb.log.info(f"Summary: {tests_passed + tests_failed} tests, "
                    f"{tests_passed} passed, {tests_failed} failed  "
                    f"({assertions_passed} assertions ok)")

    if failed_tests and failed_vector:
        with open(failed_vector, "w") as f:
            for test_lines in failed_tests:
                for l in test_lines:
                    f.write(l + "\n")
                f.write("\n")
        cocotb.log.info(f"Failed tests written to {failed_vector}")

    assert tests_failed == 0, f"{tests_failed} test(s) failed (see log above)"
